apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    POSTGRES_USER: {{ required "postgres.sealedUser must contain the encrypted POSTGRES_USER" .Values.postgres.sealedUser | quote }}
    POSTGRES_PASSWORD: {{ required "postgres.sealedPassword must contain the encrypted POSTGRES_PASSWORD" .Values.postgres.sealedPassword | quote }}
  template:
    metadata:
      name: db-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
