apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend-env
    app.kubernetes.io/part-of: order-bot
data:
{{- range $key, $value := .Values.backend.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}
