spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/order_bot_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: heslo
  liquibase:
    enabled: false

#logging:
#  level:
#    org.springframework.transaction: TRACE
#    org.springframework.orm.jpa: TRACE
#    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: TRACE
#    org.springframework.web: TRACE
auth:
  secret: secret_local_123456789101112131415
  session:
    ttl-seconds: 3600_000_000

encryption:
  secret: MySuperSecretKey # Must be at least 16 characters
  algorithm: AES
