spring:
  application:
    name: order-bot
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/order_bot_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: heslo

auth:
  secret: secret_local_123456789101112131415
  session:
    ttl-seconds: 3600_000_000

encryption:
  secret: MySuperSecretKey
  algorithm: AES
